---
- name: Deploy Docker Image on EC2 Instance
  hosts: ec2_instance
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker Image
      docker_image:
        name: otimtony/django-gpt-cicd
        tag: "{{ lookup('env', 'BUILD_ID') }}"
        pull: yes

    - name: Run Docker Container
      docker_container:
        name: django-gpt-cicd
        image: otimtony/django-gpt-cicd:{{ lookup('env', 'BUILD_ID') }}
        state: started
        restart_policy: always